### ISSUE TITLE
ProtoXtruder depth

### ISSUE THREAD

**Issue by GijsvanDulmen** [nhchiu/VoronMods#14]
Thanks for the lovely extruder! Running it right now and was wondering about a few design decisions. It seems the extruder could become even less in depth by moving the large gear which transfer to the other two a bit to the front as well. So it picks up the two gears in the middle of the large gear instead of all the way at the end. 

So I was wondering why you didn't opted for a less depth version of the ProtoXtruder. My toolhead is tiny and a few mm's less would even make it a better candidate for this toolhead (K3).

**Comment by nhchiu** [comment]
> Thanks for the lovely extruder! Running it right now and was wondering about a few design decisions. It seems the extruder could become even less in depth by moving the large gear which transfer to the other two a bit to the front as well. So it picks up the two gears in the middle of the large gear instead of all the way at the end.
> 
> So I was wondering why you didn't opted for a less depth version of the ProtoXtruder. My toolhead is tiny and a few mm's less would even make it a better candidate for this toolhead (K3).

Hello! Thanks for your question. It's because the front metal part of the extrusion gear is about half way the depth of the teeth bellow. So if the large gear moves any forward, the metal part will block the gears from meshing together.

![image](https://github.com/nhchiu/VoronMods/assets/14959712/0724e8cc-687e-4f57-94e4-a4700f0f6e4c)
![image](https://github.com/nhchiu/VoronMods/assets/14959712/395dad31-ef98-46f2-b19f-4fe2087df4e9)

Hope the screenshots explain what I was trying to say.

**Comment by GijsvanDulmen** [comment]
Thanks for the info @nhchiu ! That was less obvious then expected ;-)

Too bad.. cause it would really help the extruder become less in depth. Hope there will be other gears in the future which skip that little piece of "nothing".

**Comment by nhchiu** [comment]
> Thanks for the info @nhchiu ! That was less obvious then expected ;-)
> 
> Too bad.. cause it would really help the extruder become less in depth. Hope there will be other gears in the future which skip that little piece of "nothing".

Yeah I want to get rid of the unnecessary extra depth too.
But, don't feel bad cause Haldis, the company making the HGX gears, has made a new version with slimmer gears and some other tweaks.
Currently there's no gear kit available but you can see the extruder they have here:
https://hs3dprinter.com/products/hgx
