### ISSUE TITLE
[Question] Are any of the standard CW2 parts compatible with the Large Gear CW2 assembly?

### ISSUE THREAD

**Issue by tehniemer** [nhchiu/VoronMods#15]
Like the title states, I'm wondering if I can use any of my existing CW2 parts, like the latch, latch shuttle, cable cover, and chain anchor with your version or if they differ from the original version files?

**Comment by nhchiu** [comment]
> Like the title states, I'm wondering if I can use any of my existing CW2 parts, like the latch, latch shuttle, cable cover, and chain anchor with your version or if they differ from the original version files?

Hello. Unfortunately none of them are the same as the stock CW2 part.

**Comment by tehniemer** [comment]
Okay, thanks for confirming
