### ISSUE TITLE
Can you use LGX-lite gears

### ISSUE THREAD

**Issue by Plum6767** [nhchiu/VoronMods#17]
Hello,

is it possible to reuse the internals of an lgx-lite, rather than purchase a hgx set?

**Comment by nhchiu** [comment]
Hello. Which mod are you referring to?

**Comment by Plum6767** [comment]
The Hummingbird extruder

**Comment by nhchiu** [comment]
Sorry I didn't make a version for LGX lite gears as it is basically the same footprint as LGX lite. (And you can just use LGX lite)
