### ISSUE TITLE
HGX Oblique Gears possible in Large Gear CW2?

### ISSUE THREAD

**Issue by ghost** [nhchiu/VoronMods#19]
Hello, would the HGX Oblique Gears fit in the same way?

https://a.aliexpress.com/_EIxYxEV

**Comment by nhchiu** [comment]
No, the size is different.
It can be used with this design: https://github.com/nhchiu/3DPrinter-Designs/tree/main/ProtoXtruder_2.0
But there's not one with the CW2  form factor.

**Comment by ghost** [comment]
Thank you
