### ISSUE TITLE
Large Gear Clockworks2 HGX lite gear wheel aligning

### ISSUE THREAD

**Issue by richard9999999999** [nhchiu/VoronMods#21]
Hello, I have built HGX lite version and noticed a following problem:
The middle gear has axial play about 1mm. Yes, it doesn't need to be a problem however I see that:
- when the middle gear is in a position nearest to the stepper, the stepper's gear still isn't engaged in its full thickness to the middle gear. Plus in this position the middle gear and extruding gears are not fully engaged (in thickness)
- when the middle gear is in position nearest to the part cooling fan, the stepper's gear is engaged 1mm less than in the above case
The steppers have specified 6mm from the base plate to top of gear wheel (mine has 6.5mm) so it seems your extruder's base plate is just too thick..

I modified "motor_plate_a-HGX" for my the test purpose: I made the base plate (where stepper is mounted) 1mm thinner plus I made the cutout for the middle wheel 0.8mm less deep and also shifted the seat for middle gear bearing 0.8mm away from the stepper. Plus of course I had to do make "motor_plate_b" 1mm thicker..
Plus after this my mode there is a problem with heatset inserts (both for PCB) which also need to be shifted 1mm (besides I suppose this way they will receive more contact distance when plugged in): I have made that by forcing them in appropriate direction while seating of inserts and filling the created gaps using CA glue.

I also noticed that step CAD file doesn't contain correct bearing seat for HGX in motor_plate_a I suppose it is LGX version file? If yes, please could you share also HGX CAD file?

Thanks,
Richard

**Comment by nhchiu** [comment]
1. Yes the gears aren't designed to be fully overlapping depth-wise. That's a trade off of taking the length of screws, the filament path, position of heatset inserts, and so on, into consideration and not to causing interference or having super thin walls.

2. The positions of the PCB mounting inserts should be matching those on the stock CW2. But feel free to modify it to make a better fit for the PCB you have.

3. Both the HGX and LGX parts are included in the STEP file and the parts are named accordingly.

**Comment by richard9999999999** [comment]
1) The stepper gear is 4mm wide. You arrangement makes floating of gear overlapping somewhere between 3.5mm and 2.5mm.. I think 2.5mm overlapping from 4mm plastic/metal gear contact doesn't sound great in term of function/longevity, that's the reason I tried to solve it in my case. However I may be wrong..

I have made just quick and simple mod which tries to solve the problem while maintaining the same screws and filament path. Heatset inserts can be solved also (which I didn't chose to do in the model). Yes, the back plate is 1mm thinner than your original in the thickest place but it has the same thickness in the thinnest place and it is much more thick/robust than CW2 motor plate..

2. OK, I mentioned PCB holding inserts just because my "quick and simple" mod makes the rear one partly in air.. It is doable however. When you mention that the inserts maintain CW2 position I suppose you meant just position in the axle parallel to stepper axle and in vertical axle. In horizontal axle the position is shifted some millimeters to right (when viewing to stealthbutner from front). It is due to larger dimensions of the gear mechanism I suppose..

3. I found that now, thank you

BTW thank you for your work, I appreciate it.

**Comment by nhchiu** [comment]
> 1. The stepper gear is 4mm wide. You arrangement makes floating of gear overlapping somewhere between 3.5mm and 2.5mm.. I think 2.5mm overlapping from 4mm plastic/metal gear contact doesn't sound great in term of function/longevity, that's the reason I tried to solve it in my case. However I may be wrong..
> 
> I have made just quick and simple mod which tries to solve the problem while maintaining the same screws and filament path. Heatset inserts can be solved also (which I didn't chose to do in the model). Yes, the back plate is 1mm thinner than your original in the thickest place but it has the same thickness in the thinnest place and it is much more thick/robust than CW2 motor plate..

I agree. It's not ideal and I don't like it either. But I haven't got time to fix it yet.

> 2. OK, I mentioned PCB holding inserts just because my "quick and simple" mod makes the rear one partly in air.. It is doable however. When you mention that the inserts maintain CW2 position I suppose you meant just position in the axle parallel to stepper axle and in vertical axle. In horizontal axle the position is shifted some millimeters to right (when viewing to stealthbutner from front). It is due to larger dimensions of the gear mechanism I suppose..

No I mean the exact 3D position. The stock CW2 has a PCB spacer.

**Comment by richard9999999999** [comment]
>>No I mean the exact 3D position. The stock CW2 has a PCB spacer.

OK. Still it is strange that even when I don't use spacer I have problem to fit my SB2040 board under the cover (I need to cut a heatsink a bit). However it is just a minor annoyance..

Thanks for answers.
