### ISSUE TITLE
Hummingbird Extruder: Gears axial movements

### ISSUE THREAD

**Issue by fifonik** [nhchiu/VoronMods#22]
Thanks a lot, the feeder looks very good and 3D printing friendly.

I've just printed it and see some axial movements on all gears (~0.5mm).
I compared it with anther model for the gears set from printables (I printed earlier) and noticed that the gap is slightly smaller there (~0.3mm, measured in slicer), so there is almost no such axial gears movement.
Am I supposed to use some washers with this model?

Thanks.

**Comment by nhchiu** [comment]
Sorry I don't know which extruder you are referring to.

For most extruders, the axial play is fine. The gears will find their own happy places.
You don't need to add washers in there.

**Comment by fifonik** [comment]
Ah, sorry. I thought this git is for one extruder only (followed the link from printables and then clicked 'Issues').
I'm talking about Hummingbird (added extruder in the ticket's title)

**Comment by nhchiu** [comment]
> Ah, sorry. I thought this git is for one extruder only (followed the link from printables and then clicked 'Issues'). I'm talking about Hummingbird (added extruder in the ticket's title)

No problem. Then the gap is fine.
I left it a bit wider due to possible errors in the measurements I've done. In next update I will tweak it to have a smaller gap (to the same as the ProtoXtruder). But it should work fine as it is now.
