### ISSUE TITLE
This is not an issue but a question about the ProtoXtruder

### ISSUE THREAD

**Issue by erlis** [nhchiu/VoronMods#8]
Why would the Klipper config be different from the settings I have with the lgx lite? 

I'm considering reusing an old lgx lite I have around and use it's internal to use this protoXtruder with my mantis xol,  and see what results I'll get...

**Comment by nhchiu** [comment]
Sorry, I don't have a Bondtech LGX lite.

**Comment by erlis** [comment]
can you add a source for the 16mm shaft? I'm still searching and I can't find it yet... were did you get yours? Preferably in the US so I don't have to wait that long

**Comment by nhchiu** [comment]
>  find it yet... were did you get yours? Preferably in the US so I don't have to wait that long

It is included in the HGX lite gear kit.
If you are using the gears of LGX lite, you can probably reuse the shafts in it too.

**Comment by erlis** [comment]
> > find it yet... were did you get yours? Preferably in the US so I don't have to wait that long
> 
> It is included in the HGX lite gear kit. If you are using the gears of LGX lite, you can probably reuse the shafts in it too.

Thanks, will look into it, I wasn't sure the shafts on the LGX Lite will be the same.
